name: Checkout Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up KinD cluster
      uses: helm/kind-action@v1.0.0
      with:
        version: v0.24.0  # Specify the KinD version you want to use

    - name: Verify cluster
      run: kubectl get nodes
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: loop over deployments
      run: |
        for dir in deployments/*/
        do
            echo "Building and pushing $dir"
            app=${dir#deployments/}
            app=${app%/}

            echo "Building and pushing $dir on $app"
            cp -r deployments/package/py/dockerfile deployments/$app/dockerfile

            docker build -t ${{ secrets.DOCKER_USERNAME }}/$app:latest $dir
            docker push ${{ secrets.DOCKER_USERNAME }}/$app:latest
        done

    - name: Deploy applications
      run: bash ./deploy.sh

    - name: set username and emaim
      run: |
        git config --global user.email "${{ secrets.USER_EMAIL }}"
        git config --global user.name "${{ secrets.DOCKER_USERNAME }}"

    - name: create new brach
      run: |
        git checkout -b ${{ github.run_id }}
        git add .
        git commit -m "Deployed applications"
        git push origin ${{ github.run_id }}

    - name: switch to branch
      run: |
        git checkout ${{ github.run_id }}
        git push origin ${{ github.run_id }}

    - name: check-in manifest folder
      run: |
        git add .
        git commit -m "Deployed applications"
        git push origin ${{ github.run_id }}

    - name: create PR
      run: |
        gh pr create --title "Deployed applications" --body "Deployed applications" --base main --head ${{ github.run_id }} 